// ユニット定義

'use strict';

var exports = exports || undefined;

var pcrunit = exports || pcrunit || {};

//_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

// プレイヤーユニット情報一覧(隊列順)
pcrunit.PC_UNIT_INFO_LIST = [
  ['rima', 'リマ', 'リマ.jpg', true],
  ['miyako', 'ミヤコ', 'ミヤコ.jpg', true],
  ['kuuka', 'クウカ', 'クウカ.jpg', true],
  ['jun', 'ジュン', 'ジュン.jpg', true],
  ['kuuka_ooedo', 'クウカ(オーエド)', 'クウカ(オーエド).jpg', true],
  ['kaori', 'カオリ', 'カオリ.jpg', true],
  ['tsumugi_halloween', 'ツムギ(ハロウィン)', 'ツムギ(ハロウィン).jpg', true],
  ['rei_newyear', 'レイ(ニューイヤー)', 'レイ(ニューイヤー).jpg', true],
  ['rin_deremas', 'リン(デレマス)', 'リン(デレマス).jpg', true],
  ['pecorine', 'ペコリーヌ', 'ペコリーヌ.jpg', true],
  ['pecorine_princess', 'ペコリーヌ(プリンセス)', 'ペコリーヌ(プリンセス).jpg', true],
  ['ruka', 'ルカ', 'ルカ.jpg', true],
  ['kokkoro_newyear', 'コッコロ(ニューイヤー)', 'コッコロ(ニューイヤー).jpg', true],
  ['nozomi', 'ノゾミ', 'ノゾミ.jpg', true],
  ['muimi', 'ムイミ', 'ムイミ.jpg', true],
  ['makoto', 'マコト', 'マコト.jpg', true],
  ['kaya', 'カヤ', 'カヤ.jpg', true],
  ['hiyori_newyear', 'ヒヨリ(ニューイヤー)', 'ヒヨリ(ニューイヤー).jpg', true],
  ['ninon_ooedo', 'ニノン(オーエド)', 'ニノン(オーエド).jpg', true],
  ['akino', 'アキノ', 'アキノ.jpg', true],
  ['makoto_summer', 'マコト(サマー)', 'マコト(サマー).jpg', true],
  ['jun_summer', 'ジュン(サマー)', 'ジュン(サマー).jpg', true],
  ['matsuri', 'マツリ', 'マツリ.jpg', true],
  ['chloe', 'クロエ', 'クロエ.jpg', true],
  ['matsuri_halloween', 'マツリ(ハロウィン)', 'マツリ(ハロウィン).jpg', true],
  ['eriko_valentine', 'エリコ(バレンタイン)', 'エリコ(バレンタイン).jpg', true],
  ['ayane_christmas', 'アヤネ(クリスマス)', 'アヤネ(クリスマス).jpg', true],
  ['ruka_summer', 'ルカ(サマー)', 'ルカ(サマー).jpg', true],
  ['tsumugi', 'ツムギ', 'ツムギ.jpg', true],
  ['inori', 'イノリ', 'イノリ.jpg', true],
  ['hiyori', 'ヒヨリ', 'ヒヨリ.jpg', true],
  ['misogi', 'ミソギ', 'ミソギ.jpg', true],
  ['ayane', 'アヤネ', 'アヤネ.jpg', true],
  ['misogi_halloween', 'ミソギ(ハロウィン)', 'ミソギ(ハロウィン).jpg', true],
  ['tamaki', 'タマキ', 'タマキ.jpg', true],
  ['tomo', 'トモ', 'トモ.jpg', true],
  ['chieru', 'チエル', 'チエル.jpg', true],
  ['tamaki_summer', 'タマキ(サマー)', 'タマキ(サマー).jpg', true],
  ['eriko', 'エリコ', 'エリコ.jpg', true],
  ['pecorine_summer', 'ペコリーヌ(サマー)', 'ペコリーヌ(サマー).jpg', true],
  ['kurumi', 'クルミ', 'クルミ.jpg', true],
  ['djeeta', 'ジータ', 'ジータ.jpg', true],
  ['rei', 'レイ', 'レイ.jpg', true],
  ['ilya_christmas', 'イリヤ(クリスマス)', 'イリヤ(クリスマス).jpg', true],
  ['anna_summer', 'アンナ(サマー)', 'アンナ(サマー).jpg', true],
  ['christina_chrismas', 'クリスティーナ(クリスマス)', 'クリスティーナ(クリスマス).jpg', true],
  ['shizuru', 'シズル', 'シズル.jpg', true],
  ['christina', 'クリスティーナ', 'クリスティーナ.jpg', true],
  ['kurumi_christmas', 'クルミ(クリスマス)', 'クルミ(クリスマス).jpg', true],
  ['mimi', 'ミミ', 'ミミ.jpg', true],
  ['shinobu', 'シノブ', 'シノブ.jpg', true],
  ['mimi_halloween', 'ミミ(ハロウィン)', 'ミミ(ハロウィン).jpg', true],
  ['uzuki_deremas', 'ウヅキ(デレマス)', 'ウヅキ(デレマス).jpg', true],
  ['rei_halloween', 'レイ(ハロウィン)', 'レイ(ハロウィン).jpg', true],
  ['shizuru_valentine', 'シズル(バレンタイン)', 'シズル(バレンタイン).jpg', true],
  ['mahiru_ranger', 'マヒル(レンジャー)', 'マヒル(レンジャー).jpg', true],
  ['mahiru', 'マヒル', 'マヒル.jpg', true],
  ['yukari', 'ユカリ', 'ユカリ.jpg', true],
  ['monika', 'モニカ', 'モニカ.jpg', true],
  ['ninon', 'ニノン', 'ニノン.jpg', true],
  ['nozomi_christmas', 'ノゾミ(クリスマス)', 'ノゾミ(クリスマス).jpg', true],
  ['mihuyu', 'ミフユ', 'ミフユ.jpg', true],
  ['rin_ranger', 'リン(レンジャー)', 'リン(レンジャー).jpg', true],
  ['ilya', 'イリヤ', 'イリヤ.jpg', true],
  ['kaori_summer', 'カオリ(サマー)', 'カオリ(サマー).jpg', true],
  ['saren', 'サレン', 'サレン.jpg', true],
  ['anna', 'アンナ', 'アンナ.jpg', true],
  ['nanaka_summer', 'ナナカ(サマー)', 'ナナカ(サマー).jpg', true],
  ['shinobu_halloween', 'シノブ(ハロウィン)', 'シノブ(ハロウィン).jpg', true],
  ['mihuyu_summer', 'ミフユ(サマー)', 'ミフユ(サマー).jpg', true],
  ['kokkoro', 'コッコロ', 'コッコロ.jpg', true],
  ['ayumi_wonder', 'アユミ(ワンダー)', 'アユミ(ワンダー).jpg', true],
  ['ayumi', 'アユミ', 'アユミ.jpg', true],
  ['grea', 'グレア', 'グレア.jpg', true],
  ['akari_angel', 'アカリ(エンジェル)', 'アカリ(エンジェル).jpg', true],
  ['yori_angel', 'ヨリ(エンジェル)', 'ヨリ(エンジェル).jpg', true],
  ['kokkoro_summer', 'コッコロ(サマー)', 'コッコロ(サマー).jpg', true],
  ['rem', 'レム', 'レム.jpg', true],
  ['ram', 'ラム', 'ラム.jpg', true],
  ['rin', 'リン', 'リン.jpg', true],
  ['kokkoro_princess', 'コッコロ(プリンセス)', 'コッコロ(プリンセス).jpg', true],
  ['labyrista', 'ラビリスタ', 'ラビリスタ.jpg', true],
  ['mitsuki', 'ミツキ', 'ミツキ.jpg', true],
  ['hatsune_summer', 'ハツネ(サマー)', 'ハツネ(サマー).jpg', true],
  ['akari', 'アカリ', 'アカリ.jpg', true],
  ['yori', 'ヨリ', 'ヨリ.jpg', true],
  ['saren_summer', 'サレン(サマー)', 'サレン(サマー).jpg', true],
  ['miyako_halloween', 'ミヤコ(ハロウィン)', 'ミヤコ(ハロウィン).jpg', true],
  ['arisa', 'アリサ', 'アリサ.jpg', true],
  ['anne', 'アン', 'アン.jpg', true],
  ['lou', 'ルゥ', 'ルゥ.jpg', true],
  ['neneka', 'ネネカ', 'ネネカ.jpg', true],
  ['aoi_hennyuusei', 'アオイ(編入生)', 'アオイ(編入生).jpg', true],
  ['kyaru_newyear', 'キャル(ニューイヤー)', 'キャル(ニューイヤー).jpg', true],
  ['mio_deremas', 'ミオ(デレマス)', 'ミオ(デレマス).jpg', true],
  ['misato_summer', 'ミサト(サマー)', 'ミサト(サマー).jpg', true],
  ['rino', 'リノ', 'リノ.jpg', true],
  ['suzuna', 'スズナ', 'スズナ.jpg', true],
  ['suzuna_summer', 'スズナ(サマー)', 'スズナ(サマー).jpg', true],
  ['shiori', 'シオリ', 'シオリ.jpg', true],
  ['shiori_magical', 'シオリ(マジカル)', 'シオリ(マジカル).jpg', true],
  ['io', 'イオ', 'イオ.jpg', true],
  ['io_summer', 'イオ(サマー)', 'イオ(サマー).jpg', true],
  ['suzume', 'スズメ', 'スズメ.jpg', true],
  ['suzume_newyear', 'スズメ(ニューイヤー)', 'スズメ(ニューイヤー).jpg', true],
  ['emilia', 'エミリア', 'エミリア.jpg', true],
  ['kasumi', 'カスミ', 'カスミ.jpg', true],
  ['kasumi_magical', 'カスミ(マジカル)', 'カスミ(マジカル).jpg', true],
  ['rino_wonder', 'リノ(ワンダー)', 'リノ(ワンダー).jpg', true],
  ['misato', 'ミサト', 'ミサト.jpg', true],
  ['nanaka', 'ナナカ', 'ナナカ.jpg', true],
  ['yui_newyear', 'ユイ(ニューイヤー)', 'ユイ(ニューイヤー).jpg', true],
  ['kyaru', 'キャル', 'キャル.jpg', true],
  ['hatsune', 'ハツネ', 'ハツネ.jpg', true],
  ['misaki', 'ミサキ', 'ミサキ.jpg', true],
  ['luna', 'ルナ', 'ルナ.jpg', true],
  ['yui_princess', 'ユイ(プリンセス)', 'ユイ(プリンセス).jpg', true],
  ['chika_christmas', 'チカ(クリスマス)', 'チカ(クリスマス).jpg', true],
  ['suzume_summer', 'スズメ(サマー)', 'スズメ(サマー).jpg', true],
  ['kyaru_summer', 'キャル(サマー)', 'キャル(サマー).jpg', true],
  ['aoi', 'アオイ', 'アオイ.jpg', true],
  ['chika', 'チカ', 'チカ.jpg', true],
  ['maho_summer', 'マホ(サマー)', 'マホ(サマー).jpg', true],
  ['maho', 'マホ', 'マホ.jpg', true],
  ['yui', 'ユイ', 'ユイ.jpg', true],
  ['yuki', 'ユキ', 'ユキ.jpg', true],
  ['yuni', 'ユニ', 'ユニ.jpg', true],
  ['kyouka', 'キョウカ', 'キョウカ.jpg', true],
  ['misaki_halloween', 'ミサキ(ハロウィン)', 'ミサキ(ハロウィン).jpg', true],
  ['kyouka_halloween', 'キョウカ(ハロウィン)', 'キョウカ(ハロウィン).jpg', true]
];

//_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

// NPCユニット情報一覧
pcrunit.NPC_UNIT_INFO_LIST = [
  // 1番目
  ['goblingreat', 'ゴブリングレート', 'ゴブリングレート.jpg', true],
  ['wyvern', 'ワイバーン', 'ワイバーン.jpg', true],
  // 2番目
  ['rairai', 'ライライ', 'ライライ.jpg', true],
  ['wildgriffin', 'ワイルドグリフォン', 'ワイルドグリフォン.jpg', true],
  ['landsloth', 'ランドスロース', 'ランドスロース.jpg', true],
  // 3番目
  ['jackalthief', 'ジャッカルシーフ', 'ジャッカルシーフ.jpg', true],
  ['madamprism', 'マダムプリズム', 'マダムプリズム.jpg', true],
  ['megaraphan', 'メガラパーン', 'メガラパーン.jpg', true],
  ['mushufsh', 'ムシュフシュ', 'ムシュフシュ.jpg', true],
  ['raiden', 'ライデン', 'ライデン.jpg', true],
  ['seadrake', 'シードレイク', 'シードレイク.jpg', true],
  ['wraithlord', 'レイスロード', 'レイスロード.jpg', true],
  // 4番目
  ['cyclops', 'サイクロプス', 'サイクロプス.jpg', true],
  ['madbear', 'マッドベア', 'マッドベア.jpg', true],
  ['mastersenri', 'マスターセンリ', 'マスターセンリ.jpg', true],
  ['mova', 'ムーバ', 'ムーバ.jpg', true],
  ['neputerion', 'ネプテリオン', 'ネプテリオン.jpg', true],
  ['spirithorn', 'スピリットホーン', 'スピリットホーン.jpg', true],
  ['trylocker', 'トライロッカー', 'トライロッカー.jpg', true],
  ['titanoturtle', 'ティタノタートル', 'ティタノタートル.jpg', true],
  ['darkgargoyle', 'ダークガーゴイル', 'ダークガーゴイル.jpg', true],
  // 5番目
  ['argeti', 'アルゲティ', 'アルゲティ.jpg', true],
  ['aquarios', 'アクアリオス', 'アクアリオス.jpg', true],
  ['torpedon', 'トルペドン', 'トルペドン.jpg', true],
  ['mesarthim', 'メサルティム', 'メサルティム.jpg', true],
  ['minotaur', 'ミノタウロス', 'ミノタウロス.jpg', true],
  ['twinpigs', 'ツインピッグス', 'ツインピッグス.jpg', true],
  ['karkinos', 'カルキノス', 'カルキノス.jpg', true],
  ['orleon', 'オルレオン', 'オルレオン.jpg', true],
  ['medusa', 'メデューサ', 'メデューサ.jpg', true],
  ['glutton', 'グラットン', 'グラットン.jpg', true]
];
